Fix syntax error - missing attribute
aws-samples/aws-cdk-intro-workshop pull request #190
Opened 2021-02-14 14:26 UTC by victormwenda

cdkworkshop_stack.py",
    apigw.LambdaRestApi(self, 'Endpoint', handler=hello_with_counter.handler, )
AttributeError: 'HitCounter' object has no attribute 'handler'

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2021-07-21 19:26 UTC, peterwoodworth approved these changes
Thank you very much!

2021-07-22 02:34 UTC, peterwoodworth requested changes
Hey @victormwenda, this change is great but could you please use a semantic commit message? The title of the issue will work fine 😄

2021-09-22 22:08 UTC, peterwoodworth submitted a review, later dismissed

2021-09-22 22:47 UTC, peterwoodworth approved these changes

2021-09-30 19:45 UTC, ryparker approved these changes

2021-09-30 19:47 UTC, merged