Fixed use of depreciated DynamoDB property "serverSideEncryption"
aws-samples/aws-cdk-intro-workshop pull request #214
Opened 2021-04-27 14:28 UTC by mrglover

Updated the code to use the newer "encryption: TableEncryption.AWS_MANAGED" instead of depreciated "serverSideEncryption: true".

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2021-07-21 19:24 UTC, peterwoodworth approved these changes
Looks good, thank you!

2021-07-22 02:30 UTC, peterwoodworth commented
Hey @mrglover same as the other issue, if you could have a semantic commit message that would be great 😄

2021-07-22 02:31 UTC, peterwoodworth requested changes
Please use a semantic commit message

2021-09-30 19:55 UTC, ryparker approved these changes

2021-09-30 19:56 UTC, merged