update python workshop instructions
aws-samples/aws-cdk-intro-workshop pull request #568
Opened 2022-06-17 17:20 UTC by Tianyi-W

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2022-06-17 23:49 UTC, peterwoodworth requested changes
I'm pretty concerned about the dimensions of the images here. Could you try to keep the new images around the same height and width as the previous ones?

2022-06-17 23:49 UTC, peterwoodworth commented on workshop/content/30-python/30-hello-cdk/200-lambda.md
> +4. Select __apigateway-aws-proxy__ from the __Event template__ list.
The template's actual name is `apigateway-aws-proxy`, but the dropdown the user will see still shows the full name `API Gateway AWS Proxy`
<img width="297" alt="Screen Shot 2022-06-17 at 4 39 27 PM" src="https://user-images.githubusercontent.com/44349620/174412880-88090198-5814-4330-ab9f-85836223a0f7.png">

I think I'd prefer to either clarify both, or keep the name as the same as the name seen in the dropdown menu

2022-07-13 19:55 UTC, peterwoodworth commented
@Tianyi-W Are you planning on getting back to this?

2022-07-14 14:25 UTC, Tianyi-W commented
> 
Yes, I am planning on getting back to this.

2022-07-21 17:55 UTC, peterwoodworth requested changes
These images you've added are great since they are on the newer console. What was the reasoning behind changing the specific images you did? Are there not other images that need updating?

Additionally, the other language workshops use the same images for the most part. If we are going to replace the images for one language, we should do it for all langauges. Please make sure the images you're changing are updated in all languages
Lastly, there's no need to rename the old images. You can just delete them

2022-07-21 17:55 UTC, peterwoodworth commented on workshop/content/30-python/30-hello-cdk/200-lambda.md
> +4. Select __API Gateway AWS Proxy__ from the __Event template__ list.
This change would also be necessary in the other workshops - at the least it is in TypeScript. Could you check the others and update there as well?

2022-08-29 22:27 UTC, peterwoodworth commented
Ping me if you plan to work on these changes again

2022-08-29 22:27 UTC, closed without merging